delete_record:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: pool_maintenance_tracker
    record_id:
      required: false
      selector:
        text:
